### PR TITLE
Update main.yml to fix Empty needle warning

### PR DESCRIPTION
**Pull request by cfaria**
Fix for https://github.com/roots/trellis/issues/1385
As merged by Trellis owners https://github.com/roots/trellis/pull/1388

### CODE REVIEW

**Comment by cfaria** [comment]
Ok, maybe I've tried to kill a fly with a cannon... what about using the already wp_installed var?

**Comment by cfaria** [comment]
**wp_installed** var is declared on a later hook (deploy_finalize_before) and can't be used on the main.yml task (deploy_initialize_after). I think this way is the way to go...

**Comment by codepuncher** [comment]
Hi @cfaria ,

Thanks for taking a look at this issue.

Yeah, I think I'm with you there as the vars need declaring at different points.

My only point for the PR is to resolve a previous issue; the variables defined in this task (e.g. `initialize_after_wp_installed_singlesite`) should really be prefixed with `trellis_backup_during_deploy` like `trellis_backup_during_deploy_wp_installed_singlesite` or `trellis_backup_during_deploy_initialize_after_wp_installed_singlesite`.

This is just in case someone somewhere else defines `initialize_after_wp_installed_singlesite`

Would you be able to address that and we can get this merged? I'll look to get a release out ASAP for that.

Cheers

**Comment by cfaria** [comment]
Done @codepuncher

**Comment by codepuncher** [comment]
Cheers @cfaria !

**Pull request merged**
